### ISSUE TITLE
this poop isn't working

### ISSUE THREAD

**Issue by env0id** [CURVoid/FLAKars#1]
Gas fee fetching failed due to: execution reverted
Gas fee fetching failed due to: execution reverted
Gas fee fetching failed due to: 
Traceback (most recent call last):
  File "/Users/mac/Documents/FLAKars/scripts/arbitrage.py", line 21, in <module>
    main()
  File "/Users/mac/Documents/FLAKars/scripts/arbitrage.py", line 17, in main
    arbitrages = config.get_available_arbitrages(0.001)
  File "/Users/mac/Documents/FLAKars/scripts/config/config.py", line 115, in get_available_arbitrages
    if not self.contract.available(pair_in):
  File "/Users/mac/Documents/FLAKars/scripts/contract/contract.py", line 133, in available
    available = function.call({ "from": self.owner_wallet.address })
  File "/Users/mac/.pyenv/versions/3.10.10/lib/python3.10/site-packages/web3/contract/contract.py", line 305, in call
    return call_contract_function(
  File "/Users/mac/.pyenv/versions/3.10.10/lib/python3.10/site-packages/web3/contract/utils.py", line 96, in call_contract_function
    return_data = w3.eth.call(
  File "/Users/mac/.pyenv/versions/3.10.10/lib/python3.10/site-packages/web3/eth/eth.py", line 259, in call
    return self._durin_call(transaction, block_identifier, state_override)
  File "/Users/mac/.pyenv/versions/3.10.10/lib/python3.10/site-packages/web3/eth/eth.py", line 278, in _durin_call
    return self._call(transaction, block_identifier, state_override)
  File "/Users/mac/.pyenv/versions/3.10.10/lib/python3.10/site-packages/web3/module.py", line 75, in caller
    result = w3.manager.request_blocking(
  File "/Users/mac/.pyenv/versions/3.10.10/lib/python3.10/site-packages/web3/manager.py", line 326, in request_blocking
    return self.formatted_response(
  File "/Users/mac/.pyenv/versions/3.10.10/lib/python3.10/site-packages/web3/manager.py", line 287, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/Users/mac/.pyenv/versions/3.10.10/lib/python3.10/site-packages/web3/manager.py", line 104, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 680, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 655, in cytoolz.functoolz.c_pipe
  File "/Users/mac/.pyenv/versions/3.10.10/lib/python3.10/site-packages/web3/_utils/error_formatters_utils.py", line 165, in raise_contract_logic_error_on_revert
    raise ContractLogicError("execution reverted", data=data)
web3.exceptions.ContractLogicError: execution reverted

**Comment by 402status** [comment]
kys
